# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.atjones.InventoryCleaner.InventoryCleaner
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  inv:
    description: show the InventoryCleaner help page
    usage: /<command> action
    permission: inv.help
permissions:
  inv.*:
    description: gives access to all commands
    default: op
    children:
        inv.help:
            description: shows help
            default: false
        inv.clear:
            description: clears inventory
            default: false
        inv.save:
            description: saves inventory
            default: false
        inv.load:
            description: loads saved inventory
            default: false    