# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.atjones.InventoryCleaner.InventoryCleaner
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  inv:
    description: show the InventoryCleaner help page
    usage: /<command>
    permission: inv.help
permissions:
  inv.help:
    description: gives access to the InventoryCleaner help page
    default: false